// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain
#include "UnityCG.cginc"

RWStructuredBuffer<float> _DistanceBuffer;
float2 _UV;
Texture2D<float> _CameraDepthTexture; SamplerState sampler_CameraDepthTexture;
[numthreads(1,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    _DistanceBuffer[id.x] = LinearEyeDepth(_CameraDepthTexture.SampleLevel(sampler_CameraDepthTexture, _UV, 0));
}
